id: P008266
initial_creation_type: ocr
source_metadata:
  id: bdr:W23921
  title: ཐང་སྟོང་སྙན་བརྒྱུད།
  author: ''
  volumes:
    536ef2acd9974ee6a42e551c13eefc20:
      image_group_id: I1PD36461
      title: ''
      volume_number: 1
      total_pages: 624
      base_file: v001.txt
    8710215fcdab411ea78fea6f5a310753:
      image_group_id: I1PD36462
      title: ''
      volume_number: 2
      total_pages: 664
      base_file: v002.txt
